- name: make sure pt-transport-https is installed
  apt: name=apt-transport-https state=installed

- name: add docker repo key
  apt_key: keyserver="{{ docker_keyserver }}" id="{{ docker_key_id }}" state=present

- name: add docker repo and update apt cache
  apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-trusty main" update_cache=yes state=present

- name: install docker
  apt: name=docker-engine state=present
  notify: 
    - start docker

- name: install docker-py
  pip: name=docker-py version=1.1.0 state=present
